{% set name = "kfp-server-api" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kfp-server-api-{{ version }}.tar.gz
  sha256: 81acf7b744023d4badaaa75bdcb868396e589bd20344ee6d9ee286fd06e16550


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil

test:
  imports:
    - kfp_server_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kubeflow/pipelines/tree/master/backend/api/python_http_client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: KF Pipelines API
  description: Generated python client for the KF Pipelines server API

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
